### ISSUE TITLE
Allow issue numbers in commit description (but not commit message)

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/camper-gh-bot#9]
My understanding from talking with @erictleung is that currently Commitizen allows issue numbers in the commit descriptions, but not in the commit message itself.

CamperBot will give contributors a warning if they create an issue with an issue number in the description. We should follow Commitizen's convention and allow issue numbers in the commit descriptions, though not in the commit message itself.

**Comment by avirlrma** [comment]
@QuincyLarson I would like to work on it. May I ?
Based on what I've had understood that you want the camperBot not to just give a warning but to not allow commits with isssue number in commit description at all. Am I right about this?

**Comment by raisedadead** [comment]
@QuincyLarson @aviral1701 I had PR already in WIP before this issue was logged and it will address it.

**Comment by avirlrma** [comment]
@raisedadead  @QuincyLarson Anything for a beginner to work on?

**Comment by raisedadead** [comment]
@aviral1701 you should check out the main repository for issues, we occasionally tag issues that are beginner friendly
